imports:
    - { resource: phpbb_tables.yml }

services:
    david63.creditspage.listener:
        class: david63\creditspage\event\listener
        arguments:
            - '@config'
            - '@auth'
            - '@template'
            - '@user'
            - '@controller.helper'
            - '@david63.creditspage.core.creditspage'
            - '%cpconstants%'
        tags:
            - { name: event.listener }

    david63.creditspage.admin.controller:
        class: david63\creditspage\controller\admin_controller
        arguments:
            - '@config'
            - '@request'
            - '@template'
            - '@user'
            - '@language'
            - '@log'
            - '@dbal.conn'
            - '@david63.creditspage.core.creditspage'
            - '%cpconstants%'
            - '%tables%'

    david63.creditspage.main.controller:
        class: david63\creditspage\controller\main_controller
        arguments:
            - '@controller.helper'
            - '@template'
            - '@language'

    david63.creditspage.core.creditspage:
        class: david63\creditspage\core\creditspage
        arguments:
            - '@dbal.conn'
            - '@ext.manager'
            - '%tables%'

parameters:
    cpconstants:
        form_key: 'creditspage'

        user_founder: 3

        cpuser: 1
        cpmod: 2
        cpuser_mod: 3
        cpadmin: 4
        cpuser_admin: 5
        cpmod_admin: 6
        cpuser_mod_admin: 7

        creditspage_version: '2.1.0 RC1'
