services:
    david63.creditspage.listener:
        class: david63\creditspage\event\listener
        arguments:
            - '@config'
            - '@user'			
            - '@auth'
            - '@template'
            - '@controller.helper'
            - '@david63.creditspage.core.functions'
            - '%cpconstants%'
        tags:
            - { name: event.listener }

    david63.creditspage.admin.controller:
        class: david63\creditspage\controller\admin_controller
        arguments:
            - '@config'
            - '@request'
            - '@template'
            - '@user'
            - '@language'
            - '@log'
            - '@dbal.conn'
            - '@david63.creditspage.core.functions'
            - '%cpconstants%'
            - '%tables%'

    david63.creditspage.main.controller:
        class: david63\creditspage\controller\main_controller
        arguments:
            - '@config'
            - '@request'
            - '@auth'
            - '@template'
            - '@user'
            - '@language'
            - '@controller.helper'
            - '@pagination'
            - '@david63.creditspage.core.functions'
            - '%cpconstants%'
            - '%core.root_path%'
            - '%core.php_ext%'

    david63.creditspage.core.functions:
        class: david63\creditspage\core\functions
        arguments:
            - '@dbal.conn'
            - '@ext.manager'
            - '%tables%'
            - '@language'
    _defaults:
        public: true

parameters:
    cpconstants:
        form_key: 'creditspage'

        user_founder: 3

        cpuser: 1
        cpmod: 2
        cpadmin: 4
